// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adicyrhhhoqgiugdqvqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkaWN5cmhoaG9xZ2l1Z2RxdnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3Njk0ODcsImV4cCI6MjA1MjM0NTQ4N30.jfnObmTgvdWZWyhPF88HFZcso2ubBjIZ5NoyUbk2e8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);